import type {
  ReferenceType,
  CurrencyRefType,
  MemoRef,
  BigDecimal,
  ModificationMetaData,
  CustomField,
  PhysicalAddress,
  EmailAddress,
  Line,
  LinkedTxn,
  TxnTaxDetail,
  DeliveryInfo,
} from './common.type'

/**
 * Invoice Entity
 * Extracted from official Intuit Developer documentation
 */
export interface Invoice {
  /**
   * Unique identifier for this object. Sort order is ASC by default.
   * @filterable
   */
  Id: string

  /**
   * Individual line items of a transaction. Valid Line types include SalesItemLine, GroupLine, DescriptionOnlyLine (also used for inline Subtotal lines), DiscountLine and SubTotalLine (used for the overall transaction). If the transaction is taxable there is a limit of 750 lines per transaction.
   */
  Line?: Line[]

  /**
   * Reference to a customer or job. Query the Customer name list resource to determine the appropriate Customer object for this reference. Use Customer.Id and Customer.DisplayName from that object for CustomerRef.value and CustomerRef.name, respectively.
   * @filterable
   */
  CustomerRef?: ReferenceType

  /**
   * Version number of the object. It is used to lock an object for use by one app at a time. As soon as an application modifies an object, its SyncToken is incremented. Attempts to modify an object specifying an older SyncToken fails. Only the latest version of the object is maintained by QuickBooks Online.
   */
  SyncToken?: string

  /**
   * Identifies the address where the goods are shipped from. For transactions without shipping, it represents the address where the sale took place.
   * If automated sales tax is enabled (Preferences.TaxPrefs.PartnerTaxEnabled is set to true) and automated tax calculations are being used, this field is required for an accurate sales tax calculation.
   * For international addresses - countries should be passed as 3 ISO alpha-3 characters or the full name of the country.
   * If a physical address is updated from within the transaction object, the QuickBooks Online API flows individual address components differently into the Line elements of the transaction response then when the transaction was first created:
   * Line1 and Line2 elements are populated with the customer name and company name.
   * Original Line1 through Line 5 contents, City, SubDivisionCode, and PostalCode flow into Line3 through Line5as a free format strings.
   */
  ShipFromAddr?: PhysicalAddress

  /**
   * Reference to the currency in which all amounts on the associated transaction are expressed. This must be defined if multicurrency is enabled for the company. Multicurrency is enabled for the company if Preferences.MultiCurrencyEnabled is set to true. Read more about multicurrency support here. Applicable if multicurrency is enabled for the company.
   */
  CurrencyRef?: CurrencyRefType

  /**
   * Method in which tax is applied. Allowed values are: TaxExcluded, TaxInclusive, and NotApplicable. Not applicable to US companies; required for non-US companies.
   */
  GlobalTaxCalculation?: string

  /**
   * Reference number for the transaction. If not explicitly provided at create time, this field is populated based on the setting of Preferences:CustomTxnNumber as follows:
   * If Preferences:CustomTxnNumber is true a custom value can be provided. If no value is supplied, the resulting DocNumber is null.
   * If Preferences:CustomTxnNumber is false, resulting DocNumber is system generated by incrementing the last number by 1.
   * If Preferences:CustomTxnNumber is false then do not send a value as it can lead to unwanted duplicates. If a DocNumber value is sent for an Update operation, then it just updates that particular invoice and does not alter the internal system DocNumber.
   * Note: DocNumber is an optional field for all locales except France. For France locale if Preferences:CustomTxnNumber is enabled it will not be automatically generated and is a required field. If a duplicate DocNumber needs to be supplied, add the query parameter name/value pair, include=allowduplicatedocnum to the URI.
   * @filterable
   */
  DocNumber?: string

  /**
   * Reference to the Project ID associated with this transaction. Available with Minor Version 69 and above
   * @filterable
   */
  ProjectRef?: ReferenceType

  /**
   * Identifies the e-mail address where the invoice is sent. If EmailStatus=NeedToSend, BillEmailis a required input.
   */
  BillEmail?: EmailAddress

  /**
   * The date entered by the user when this transaction occurred.
   * yyyy/MM/dd is the valid date format.
   * For posting transactions, this is the posting date that affects the financial statements. If the date is not supplied, the current date on the server is used.
   * Sort order is ASC by default.
   * @filterable
   */
  TxnDate?: string

  /**
   * Date for delivery of goods or services.
   */
  ShipDate?: string

  /**
   * Shipping provider's tracking number for the delivery of the goods associated with the transaction.
   */
  TrackingNum?: string

  /**
   * Reference to the Class associated with the transaction. Available if Preferences.AccountingInfoPrefs.ClassTrackingPerTxn is set to true. Query the Class name list resource to determine the appropriate Class object for this reference. Use Class.Id and Class.Name from that object for ClassRef.value and ClassRef.name, respectively.
   */
  ClassRef?: ReferenceType

  /**
   * Printing status of the invoice. Valid values: NotSet, NeedToPrint, PrintComplete .
   */
  PrintStatus?: string

  /**
   * Reference to the sales term associated with the transaction. Query the Term name list resource to determine the appropriate Term object for this reference. Use Term.Id and Term.Name from that object for SalesTermRef.value and SalesTermRef.name, respectively.
   * @filterable
   */
  SalesTermRef?: ReferenceType

  /**
   * Used internally to specify originating source of a credit card transaction.
   */
  TxnSource?: string

  /**
   * Zero or more related transactions to this Invoice object. The following linked relationships are supported:
   * Links to Estimate and TimeActivity objects can be established directly to this Invoice object with UI or with the API. Create, Read, Update, and Query operations are avaialble at the API level for these types of links.
   * Only one link can be made to an Estimate. Progress Invoicing is not supported via the API.
   * Links to expenses incurred on behalf of the customer are returned in the response with LinkedTxn.TxnType set to ReimburseCharge, ChargeCredit or StatementCharge corresponding to billable customer expenses of type Cash, Delayed Credit, and Delayed Charge, respectively. Links to these types of transactions are established within the QuickBooks UI, only, and are available as read-only at the API level.
   * Links to payments applied to an Invoice object are returned in the response with LinkedTxn.TxnType set to Payment. Links to Payment transactions are established within the QuickBooks UI, only, and are available as read-only at the API level.
   * Use LinkedTxn.TxnId as the ID in a separate read request for the specific resource to retrieve details of the linked object.
   */
  LinkedTxn?: LinkedTxn[]

  /**
   * Account to which money is deposited. Query the Account name list resource to determine the appropriate Account object for this reference, where Account.AccountType is Other Current Asset or Bank. Use Account.Id and Account.Name from that object for DepositToAccountRef.value and DepositToAccountRef.name, respectively.
   * Before you can use this field ensure that the company allows deposits in their invoices first. This can be found by querying the Preferences endpoint. SalesFormsPrefs.AllowDeposit must be equal to true. If you do not specify this account the payment is applied to the Undeposited Funds account.
   */
  DepositToAccountRef?: ReferenceType

  /**
   * Specifies if this invoice can be paid with online bank transfers and corresponds to the Bank transfer check box on the QuickBooks UI. Active when the company is payments-enabled, i.e., Preferences.SalesFormsPrefs.ETransactionPaymentEnabled is set to true.
   * If set to true, allow invoice to be paid with online bank transfers. The Bank transfer check box is checked on the QuickBooks UI for this invoice. True by default if the company allows invoices to be paid with ACH.
   * If set to false, online bank transfers are not allowed. The Bank transfer check box is not checked on the QuickBooks UI for this invoice.
   */
  AllowOnlineACHPayment?: boolean

  /**
   * The account location. For France locale valid values include:
   * WithinFrance
   * FranceOverseas
   * OutsideFranceWithEU
   * OutsideEU
   * For UAE, valid values include
   * ABUDHABI
   * AJMAN
   * SHARJAH
   * DUBAI
   * FUJAIRAH
   * RAS_AL_KHAIMAH
   * UMM_AL_QUWAIN
   * OTHER_GCC
   * For India locale, use state code values from the list below:
   */
  TransactionLocationType?: string

  /**
   * Date when the payment of the transaction is due. If date is not provided, the number of days specified in SalesTermRef added the transaction date will be used.
   * @filterable
   */
  DueDate?: string

  /**
   * Descriptive information about the object. The MetaData values are set by Data Services and are read only for all applications.
   */
  MetaData?: ModificationMetaData

  /**
   * User entered, organization-private note about the transaction. This note does not appear on the invoice to the customer. This field maps to the Statement Memo field on the Invoice form in the QuickBooks Online UI.
   */
  PrivateNote?: string

  /**
   * Identifies the carbon copy e-mail address where the invoice is sent. If not specified, this field is populated from that defined in Preferences.SalesFormsPrefs.SalesEmailCc. If this email address is invalid, carbon copy email is not sent.
   */
  BillEmailCc?: EmailAddress

  /**
   * User-entered message to the customer; this message is visible to end user on their transactions.
   */
  CustomerMemo?: MemoRef

  /**
   * Email status of the invoice. Valid values: NotSet, NeedToSend, EmailSent
   */
  EmailStatus?: string

  /**
   * The number of home currency units it takes to equal one unit of currency specified by CurrencyRef. Applicable if multicurrency is enabled for the company.
   */
  ExchangeRate?: number

  /**
   * The deposit made towards this invoice.
   */
  Deposit?: number

  /**
   * This data type provides information for taxes charged on the transaction as a whole. It captures the details sales taxes calculated for the transaction based on the tax codes referenced by the transaction. This can be calculated by QuickBooks business logic or you may supply it when adding a transaction. See Global tax model for more information about this element.
   * If sales tax is disabled (Preferences.TaxPrefs.UsingSalesTax is set to false) then TxnTaxDetail is ignored and not stored.
   */
  TxnTaxDetail?: TxnTaxDetail

  /**
   * Specifies if online credit card payments are allowed for this invoice and corresponds to the Credit card check box on the QuickBooks UI. Active when the company is payments-enabled, i.e., Preferences.SalesFormsPrefs.ETransactionPaymentEnabled is set to true.
   * If set to true, allow invoice to be paid with online credit card payments. The Credit card check box is checked on the QuickBooks UI for this invoice. True by default if the company allows invoices to be paid with credit cards.
   * If set to false, online credit card payments are not allowed. The Credit card check box is not checked on the QuickBooks UI for this invoice.
   */
  AllowOnlineCreditCardPayment?: boolean

  /**
   * One of, up to three custom fields for the transaction. Available for custom fields so configured for the company. Check Preferences.SalesFormsPrefs.CustomField and Preferences.VendorAndPurchasesPrefs.POCustomField for custom fields currenly configured. Click here to learn about managing custom fields.
   */
  CustomField?: CustomField

  /**
   * Identifies the address where the goods must be shipped. If ShipAddris not specified, and a default Customer:ShippingAddr is specified in QuickBooks for this customer, the default ship-to address will be used by QuickBooks.
   * For international addresses - countries should be passed as 3 ISO alpha-3 characters or the full name of the country.
   * If a physical address is updated from within the transaction object, the QuickBooks Online API flows individual address components differently into the Line elements of the transaction response then when the transaction was first created:
   * Line1 and Line2 elements are populated with the customer name and company name.
   * Original Line1 through Line 5 contents, City, SubDivisionCode, and PostalCode flow into Line3 through Line5as a free format strings.
   */
  ShipAddr?: PhysicalAddress

  /**
   * A reference to a Department object specifying the location of the transaction. Available if Preferences.AccountingInfoPrefs.TrackDepartments is set to true.
   * Query the Department name list resource to determine the appropriate department object for this reference. Use Department.Id and Department.Name from that object for DepartmentRef.value and DepartmentRef.name, respectively.
   */
  DepartmentRef?: ReferenceType

  /**
   * Identifies the blind carbon copy e-mail address where the invoice is sent. If not specified, this field is populated from that defined in Preferences.SalesFormsPrefs.SalesEmailBcc. If this email address is invalid, blind carbon copy email is not sent.
   */
  BillEmailBcc?: EmailAddress

  /**
   * Reference to the ShipMethod associated with the transaction. There is no shipping method list. Reference resolves to a string. Reference to the ShipMethod associated with the transaction. There is no shipping method list. Reference resolves to a string.
   */
  ShipMethodRef?: ReferenceType

  /**
   * Bill-to address of the Invoice. If BillAddris not specified, and a default Customer:BillingAddr is specified in QuickBooks for this customer, the default bill-to address is used by QuickBooks.
   * For international addresses - countries should be passed as 3 ISO alpha-3 characters or the full name of the country.
   * If a physical address is updated from within the transaction object, the QuickBooks Online API flows individual address components differently into the Line elements of the transaction response then when the transaction was first created:
   * Line1 and Line2 elements are populated with the customer name and company name.
   * Original Line1 through Line 5 contents, City, SubDivisionCode, and PostalCode flow into Line3 through Line5as a free format strings.
   * Starting minorversion=54 if you update the CustomerRef, the address passed using BillAddr will be honored.
   */
  BillAddr?: PhysicalAddress

  /**
   * If false or null, calculate the sales tax first, and then apply the discount. If true, subtract the discount first and then calculate the sales tax.
   */
  ApplyTaxAfterDiscount?: boolean

  /**
   * Convenience field containing the amount in Balance expressed in terms of the home currency. Calculated by QuickBooks business logic. Value is valid only when CurrencyRef is specified and available when endpoint is evoked with the minorversion=3 query parameter. Applicable if multicurrency is enabled for the company
   */
  HomeBalance?: number

  /**
   * Email delivery information. Returned when a request has been made to deliver email with the send operation.
   */
  DeliveryInfo?: DeliveryInfo

  /**
   * Indicates the total amount of the transaction. This includes the total of all the charges, allowances, and taxes. Calculated by QuickBooks business logic; any value you supply is over-written by QuickBooks.
   */
  TotalAmt?: BigDecimal

  /**
   * Sharable link for the invoice sent to external customers. The link is generated only for invoices with online payment enabled and having a valid customer email address. Include query param `include=invoiceLink` to get the link back on query response.
   */
  InvoiceLink?: string

  /**
   * A reference to the Recurring Transaction. It captures what recurring transaction template the Invoice was created from.
   */
  RecurDataRef?: ReferenceType

  /**
   * Reference to the TaxExepmtion ID associated with this object. Available for companies that have automated sales tax enabled.
   * TaxExemptionRef.Name: The Tax Exemption Id for the customer to which this object is associated. This Id is typically issued by the state.
   * TaxExemptionRef.value: The system-generated Id of the exemption type.
   * For internal use only
   */
  TaxExemptionRef?: ReferenceType

  /**
   * The balance reflecting any payments made against the transaction. Initially set to the value of TotalAmt. A Balance of 0 indicates the invoice is fully paid. Calculated by QuickBooks business logic; any value you supply is over-written by QuickBooks. If you process a linked transaction against a specific transaction, the balance value won't change. It will remain the same.
   * @filterable
   */
  Balance?: number

  /**
   * Total amount of the transaction in the home currency. Includes the total of all the charges, allowances and taxes. Calculated by QuickBooks business logic. Value is valid only when CurrencyRef is specified. Applicable if multicurrency is enabled for the company.
   */
  HomeTotalAmt?: number

  /**
   * Denotes how ShipAddr is stored: formatted or unformatted. The value of this flag is system defined based on format of shipping address at object create time.
   * If set to false, shipping address is returned in a formatted style using City, Country, CountrySubDivisionCode, Postal code.
   * If set to true, shipping address is returned in an unformatted style using Line1 through Line5 attributes.
   */
  FreeFormAddress?: boolean

  /**
   * Deprecated flag to allow online payments. In use before AllowOnlineCreditCardPayment and AllowOnlineACHPayment flags existed and provided to maintain backward compatibility.
   * If set to true, this invoice was created before AllowOnlinePayment was deprecated and denotes both CC and ACH payments are allowed. In addition, the AllowOnlineCreditCardPayment and AllowOnlineACHPayment flags must be set to true.
   * If set to false, this invoice was created after the AllowOnlinePayment flag was deprecated and is not used.
   * Do not modify.
   */
  AllowOnlinePayment?: boolean

  /**
   * Flag to allow payments from legacy Intuit Payment Network (IPN). Provided to maintain backward compatibility and must always be set to false. Do not modify
   */
  AllowIPNPayment?: boolean

  /**
   * Unique identifier for this object.
   * @filterable
   */
  id?: string
}
