import type {
  ReferenceType,
  CurrencyRefType,
  BigDecimal,
  ModificationMetaData,
  PhysicalAddress,
  Line,
  LinkedTxn,
  TxnTaxDetail,
} from './common.type'

/**
 * Purchase Entity
 * Extracted from official Intuit Developer documentation
 */
export interface Purchase {
  /**
   * Unique identifier for this object. Sort order is ASC by default.
   * @filterable
   */
  Id: string

  /**
   * Individual line items of a transaction. Valid Line types include ItemBasedExpenseLine (Available if Preferences.ProductAndServicesPrefs.ForPurchase is set to true) and AccountBasedExpenseLine
   */
  Line?: Line[]

  /**
   * Payment Type can be: Cash, Check, or CreditCard.
   */
  PaymentType?: string

  /**
   * Specifies the account reference to which this purchase is applied based on the PaymentType. A type of Check should have bank account, CreditCard should specify credit card account, etc. Query the Account name list resource to determine the appropriate Account object for this reference. Use Account.Id and Account.Name from that object for AccountRef.value and AccountRef.name, respectively.
   */
  AccountRef?: ReferenceType

  /**
   * Version number of the object. It is used to lock an object for use by one app at a time. As soon as an application modifies an object, its SyncToken is incremented. Attempts to modify an object specifying an older SyncToken fails. Only the latest version of the object is maintained by QuickBooks Online.
   */
  SyncToken?: string

  /**
   * Reference to the currency in which all amounts on the associated transaction are expressed. This must be defined if multicurrency is enabled for the company.
   * Multicurrency is enabled for the company if Preferences.MultiCurrencyEnabled is set to true. Read more about multicurrency support here. Required if multicurrency is enabled for the company.
   */
  CurrencyRef?: CurrencyRefType

  /**
   * The date entered by the user when this transaction occurred. For posting transactions, this is the posting date that affects the financial statements. If the date is not supplied, the current date on the server is used.
   * Sort order is ASC by default.
   * @filterable
   */
  TxnDate?: string

  /**
   * PrintStatus is applicable only for Check.  Ignored for CreditCardcharge or refund. Valid values: NotSet, NeedToPrint, PrintComplete.
   */
  PrintStatus?: string

  /**
   * Address to which the payment should be sent. This attribute is applicable only for Check. Ignored for CreditCard charge or refund.
   * If a physical address is updated from within the transaction object, the QuickBooks Online API flows individual address components differently into the Line elements of the transaction response then when the transaction was first created:
   * Line1 and Line2 elements are populated with the customer name and company name.
   * Original Line1 through Line 5 contents, City, SubDivisionCode, and PostalCode flow into Line3 through Line5as a free format strings.
   */
  RemitToAddr?: PhysicalAddress

  /**
   * Used internally to specify originating source of a credit card transaction.
   */
  TxnSource?: string

  /**
   * Zero or more transactions linked to this object. The LinkedTxn.TxnType can be set to ReimburseCharge. The LinkedTxn.TxnId can be set as the ID of the transaction.
   */
  LinkedTxn?: LinkedTxn[]

  /**
   * Method in which tax is applied. Allowed values are: TaxExcluded, TaxInclusive, and NotApplicable.
   */
  GlobalTaxCalculation?: string

  /**
   * The account location. Valid values include:
   * WithinFrance
   * FranceOverseas
   * OutsideFranceWithEU
   * OutsideEU
   * For France locales, only.
   */
  TransactionLocationType?: string

  /**
   * Descriptive information about the object. The MetaData values are set by Data Services and are read only for all applications.
   */
  MetaData?: ModificationMetaData

  /**
   * Reference number for the transaction. If not explicitly provided at create time, this field is populated based on the setting of Preferences:OtherPrefs:NameValue.Name = VendorAndPurchasesPrefs.UseCustomTxnNumbers as follows:
   * If Preferences:OtherPrefs:NameValue.Name = VendorAndPurchasesPrefs.UseCustomTxnNumbers is true a custom value can be provided; duplicate values are not accepted. If no value is supplied, the resulting DocNumber is null.
   * If Preferences:OtherPrefs:NameValue.Name = VendorAndPurchasesPrefs.UseCustomTxnNumbers is false, resulting DocNumber is system generated by incrementing the last number by 1.
   * For Cash/CreditCard transactions, throws an error when duplicate DocNumber is sent in the request. For Check transactions, error is thrown when duplicate DocNumber is sent in the request and Preferences:OtherPrefs:NameValue.Name = WarnDuplicateCheckNumber is true. Recommended best practice: check the setting of Preferences:OtherPrefs:NameValue.Name = VendorAndPurchasesPrefs.UseCustomTxnNumbers before setting DocNumber. If a duplicate DocNumber needs to be supplied, add the query parameter name/value pair, include=allowduplicatedocnum to the URI. Sort order is ASC by default.
   * @filterable
   */
  DocNumber?: string

  /**
   * User-entered, organization-private note about the transaction. This field maps to the Memo field on the Expense form in the QuickBooks UI.
   */
  PrivateNote?: string

  /**
   * False—it represents a charge. True—it represents a refund. Valid only for CreditCardpayment type. Validation Rules: Valid only for CreditCardtransactions.
   */
  Credit?: boolean

  /**
   * This data type provides information for taxes charged on the transaction as a whole. It captures the details sales taxes calculated for the transaction based on the tax codes referenced by the transaction. This can be calculated by QuickBooks business logic or you may supply it when adding a transaction. See Global tax model for more information about this element. If sales tax is disabled (Preferences.TaxPrefs.UsingSalesTax is set to false) then TxnTaxDetail is ignored and not stored.
   */
  TxnTaxDetail?: TxnTaxDetail

  /**
   * Reference to a PaymentMethod associated with this transaction. Query the PaymentMethod name list resource to determine the appropriate PaymentMethod object for this reference. Use PaymentMethod.Id and PaymentMethod.Name from that object for PaymentMethodRef.value and PaymentMethodRef.name, respectively.
   */
  PaymentMethodRef?: ReferenceType

  /**
   * For internal use.
   */
  PurchaseEx?: any // Internal use

  /**
   * The number of home currency units it takes to equal one unit of currency specified by CurrencyRef. Applicable if multicurrency is enabled for the company
   */
  ExchangeRate?: number

  /**
   * A reference to a Department object specifying the location of the transaction. Available if Preferences.AccountingInfoPrefs.TrackDepartments is set to true.
   * Query the Department name list resource to determine the appropriate department object for this reference. Use Department.Id and Department.Name from that object for DepartmentRef.value and DepartmentRef.name, respectively.
   */
  DepartmentRef?: ReferenceType

  /**
   * Specifies the party with whom an expense is associated. Can be Customer, Vendor, or Employee.
   * Query the corresponding name list resource of the associated type to determine the appropriate object for this reference. Use the Id and DisplayName values from that object for EntityRef.value and EntityRef.name, respectively. Set EntityRef.type to the type of object associated with this expense. For example, if this object represents a purchase from a vendor, then set EntityRef.type to Vendor and query the Vendor resource for the appropriate object to reference.
   */
  EntityRef?: ReferenceType

  /**
   * Include the supplier in the annual TPAR. TPAR stands for Taxable Payments Annual Report. The TPAR is mandated by ATO to get the details payments that businesses make to contractors for providing services. Some government entities also need to report the grants they have paid in a TPAR.
   */
  IncludeInAnnualTPAR?: boolean

  /**
   * Indicates the total amount of the transaction. This includes the total of all the charges, allowances, and taxes. Calculated by QuickBooks business logic; any value you supply is over-written by QuickBooks.
   */
  TotalAmt?: BigDecimal

  /**
   * A reference to the Recurring Transaction. It captures what recurring transaction template the Purchase was created from.
   */
  RecurDataRef?: ReferenceType

  /**
   * Unique identifier for this object.
   * @filterable
   */
  id?: string
}
