import type { TaxRateDetails } from './common.type'

/**
 * TaxService Entity
 * Extracted from official Intuit Developer documentation
 */
export interface TaxService {
  /**
   * Name of new tax code. To query list of currently defined tax codes, use the TaxCode endpoint.
   */
  TaxCode?: string

  /**
   * Container to hold one or more tax rate specifications.
   */
  TaxRateDetails?: TaxRateDetails[]

  /**
   * The id of the newly created tax code. This is generated by Data Services and returned in the response code.
   */
  TaxCodeId?: string
}
